### ISSUE TITLE
disable builtin assume warnings?

### ISSUE THREAD

**Issue by Manu343726** [foonathan/debug_assert#12]
Hi,

When using cppast I found that my clang 3.9 build warns about side effects in the assume expression:

```
cppast/external/type_safe/external/debug_assert/debug_assert.hpp:315:40: warning: the argument to '__builtin_assume' has side effects that will be discarded [-Wassume]

cppast/external/type_safe/external/debug_assert/debug_assert.hpp:60:70: note: expanded from macro 'DEBUG_ASSERT_ASSUME'
#define DEBUG_ASSERT_ASSUME(Expr) static_cast<void>(__builtin_assume(Expr), 0)
                                                                     ^~~~
```

(Note `debug_assert:60` is the line where `DEBUG_ASSERT_ASSUME()` is defined with clang).

I was wondering if we could wrap the debug_assert header with pragmas to ignore this warning:

``` cpp
#ifdef __CLANG__
#pragma clang diagnostic push
#pragma clang diagnostic ignore "-Wassume"
#endif // __CLANG__

...

#ifdef __CLANG__
#pragma clang diagnostic pop
#endif // __CLANG__
```

I would like debug_assert to not trigger any warning in order to use it on -Werror enabled projects.

**Comment by foonathan** [comment]
This is just a bug in that clang version though as it ignores the pure attribute.

Anyways, if you do a PR I'll merge.
