### ISSUE TITLE
Logging Extension

### ISSUE THREAD

**Issue by feddischson** [foonathan/debug_assert#15]
Hi Jonathan,

I came across your assert functionality while searching for a effective C++ logging facility, so this is more a question or feature request.

What I was looking for is some C++ functionality which provides
 - a generic logging functionality with log-levels, where the applied log-level is defined during compile time 
 - no overhead for a log-statement with a higher level than defined
 - almost no pre-processor usage
 - modular realization what it is done with a 'log entry', e.g. just printing it or putting it into a ring-buffer

Wouldn't it be a very similar functionality than with your assert headers? Maybe it is very easy to extend this library and to have some commonalities between logging and assertion. What do you think?

BR Chris

**Comment by foonathan** [comment]
This is out of scope for this library, it is just about assertions. There are good logging libraries out there, some very tiny ones even.

**Comment by feddischson** [comment]
Ok thanks for this feedback.
Which tiny logging library do you mean? Could you make an example?

**Comment by foonathan** [comment]
This one, for example, but there are others: https://github.com/martinmoene/clue
