### ISSUE TITLE
Replacing C++ headers with C headers

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [foonathan/debug_assert#21]
Hello!

I see that the project is in `maintenance only` mode, but I still would like to ask: Would it be possible to replace `<cstdlib>` and `<cstdio>` includes with `<stdlib.h>` and `<stdio.h>` respectively (and change `std::` to `::`)?

The reason I ask is because I'd like to use you library in a cross-platform library that's intended to run on Arduino. For whatever reason at least some toolchains (e.g. Arduino Nano) don't provide the C++ standard library headers, even those referencing C standard library. I've already wrote my own "very unique and more better" version of your library, but I'd like not to re-invent a wheel, especially if I'll make a square one.

Best regards.

**Comment by foonathan** [comment]
Sure, no problem. Let me know if that works.

**Comment by Innokentiy-Alaytsev** [comment]
Everything works. Thanks a lot!
