### ISSUE TITLE
Can you provide this under MIT license?

### ISSUE THREAD

**Issue by henrygab** [foonathan/debug_assert#22]
This library is used by your [type_safe](https://github.com/foonathan/type_safe) library, which uses the MIT license.  The MIT license is more mainstream (read: accepted and pre-authorized for use), so it would just smooth the use.

If not, that's OK.  I'm OK with the existing license, but anything to make this easier for folks to use is a "Good Thing" in my book.

BTW, really appreciate the type_safe library!

**Comment by foonathan** [comment]
Changing the license requires asking all existing contributors, which is a bit annoying.

Another alternative would be to remove the debug_assert dependency from type_safe. I consider it to be a bit over-engineered at this point, and it is really only used for two things: precondition checks and internal assertions. I'd welcome a PR that just adds two custom macros to type safe for assertions, similar to the implementation in e.g. lexy: https://github.com/foonathan/lexy/blob/main/include/lexy/_detail/assert.hpp
