### ISSUE TITLE
Deprecation warning with cmake version >= 3.27

### ISSUE THREAD

**Issue by bduminiuc** [foonathan/debug_assert#23]
Upgrading cmake, I've received the deprecation warning:
```
[cmake] CMake Deprecation Warning at external/debug_assert/CMakeLists.txt:5 (cmake_minimum_required):
[cmake]   Compatibility with CMake < 3.5 will be removed from a future version of
[cmake]   CMake.
[cmake] 
[cmake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
[cmake]   CMake that the project does not need compatibility with older versions.
```
The warning is about this line:
```
cmake_minimum_required(VERSION 3.1)
```

My cmake version is:
```
$ cmake --version
cmake version 3.27.6
```

Referring to the cmake [documentation](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-settings):
> Changed in version 3.27: Compatibility with versions of CMake older than 3.5 is deprecated...

Could it be updated?

**Comment by foonathan** [comment]
> Could it be updated?

Yes. Can you do a PR that updates it to at least 3.5? It'll be fixed quicker that way ;)
