### ISSUE TITLE
Assertion failure backtrace

### ISSUE THREAD

**Issue by Manu343726** [foonathan/debug_assert#9]
Would you consider adding an optional feature for returning/printing the backtrace of a failure?
Here's an example of backward-cpp usage: https://github.com/Manu343726/siplasplas/blob/master/include/siplasplas/utility/error_logger.hpp#L38

**Comment by foonathan** [comment]
I think that is out of scope for this library, you can easily define your own handler that does that.

**Comment by Manu343726** [comment]
you're right, thanks
